---
- name: ensure required packages are installed
  tags: [ install_packages ]
  dnf:
    name: "{{ required_rpm_pakcages }}"
    state: present

- name: validate virtualization extensions are available to this host
  tags: [validate_libvirt, libvirt_setup]
  include_tasks: validate.yml
  when: not cicd_test|bool

- name: enable libvirt services
  tags: [libvirt_setup, libvirt_services]
  service:
    name: "{{ libvirt_service }}"
    enabled: yes
    state: started
  loop: "{{ libvirt_services }}"
  loop_control:
    loop_var: libvirt_service

- name: start tuned profile virtual-host
  tags: [libvirt_setup, libvirt_tuned]
  shell: |
   set -o pipefail && tuned-adm profile virtual-host
  register: start_tuned
  changed_when: start_tuned.rc != 0
  args:
    executable: /bin/bash

- name: Configure libvirt network
  tags: [libvirt_setup, libvirt_networks]
  loop: "{{ libvirt_networks }}"
  loop_control:
    loop_var: libnet
  vars:
    net_name: "{{ libnet.name }}"
    net_mode: "{{ libnet.mode }}"
    net_create: "{{ libnet.create }}"
    net_bridge: "{{ libnet.bridge_name }}"
  include_tasks: libvirt_networks.yml
  when: not cicd_test|bool

- name: configure libvirt storage pool
  tags: [libvirt_setup, libvirt_storage]
  include_tasks: storage_pool.yml
  when: not cicd_test|bool
  loop: "{{ libvirt_host_storage_pools }}"
  loop_control:
    loop_var: libpool

- name: Make libvirt accessible by non-root user
  tags: [libvirt_setup, libvirt_user_mode]
  import_tasks: user_libvirt.yml
  when: enable_libvirt_admin_user|bool

#- name: validate variables are defined
#  import_tasks: verify_variables.yml
#

- name: configure shell extras
  import_tasks: configure_shell.yml
  when: configure_shell|bool  


